# Generated by Django 4.2.1 on 2023-06-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30, null=True)),
                ('t_desc', models.TextField(blank=True, null=True)),
                ('t_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('t_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('t_name',),
                'unique_together': {('t_name', 't_created')},
            },
        ),
    ]
